import { Photo } from "@/types";

const photos: Photo[] = [
  {
    type: "photo",
    id: "travel/23229339384_b184c5b0d0_b.jpg",
    category: "travel",
    title: "Untitled",
    camera: "Nikon D90",
    orientation: "banner",
  },
  {
    type: "photo",
    id: "travel/422072087_22ea7f952a_b.jpg",
    category: "travel",
    title: "blind musician",
    location: "Bangkok, Thailand",
    camera: "Nikon D70",
    orientation: "vertical",
  },
  {
    type: "photo",
    id: "travel/6300318366_0ef0aa65de_b.jpg",
    category: "travel",
    title: "Hermosa Beach",
    location: "Hermosa Beach, CA",
    camera: "Diana Camera",
  },
  {
    type: "photo",
    id: "travel/3257423319_7b723c6320_b.jpg",
    category: "travel",
    title: "White temple",
    location: "Chiang Rai, Thailand",
    camera: "Diana Camera",
  },
  {
    type: "photo",
    id: "travel/4571721717_bb4f9da01a_b.jpg",
    category: "travel",
    title: "Astronomy park",
    location: "Jaipur, India",
    camera: "Olympus XA",
    orientation: "horizontal",
  },
  {
    type: "video",
    title: "Anderson .Paak - Winners circle bass cover",
    id: "9llqlSpLdRk",
    orientation: "horizontal",
  },
  {
    type: "photo",
    id: "life/23446229681_fcfcb9d7d3_b.jpg",
    category: "life",
    title: "Untitled",
    camera: "Nikon D90",
    orientation: "vertical",
  },
  {
    type: "photo",
    id: "travel/3272890577_a2d4fb7fef_b.jpg",
    category: "travel",
    title: "Doi Suthep",
    location: "Chiang Mai, Thailand",
    camera: "Diana Camera",
  },
  {
    type: "photo",
    id: "travel/3269066068_0d308a7f1a_b.jpg",
    category: "travel",
    title: "Untitled",
    location: "Chiang Mai, Thailand",
    camera: "Diana Camera",
  },
  {
    type: "music",
    id: "",
  },
  {
    type: "photo",
    id: "travel/4619264427_62b8a23c57_b.jpg",
    category: "travel",
    title: "untitled",
    location: "India",
    camera: "Olympus XA",
    orientation: "horizontal",
  },
  {
    type: "photo",
    id: "travel/4405365546_e1002b5010_b.jpg",
    category: "travel",
    title: "Pallam Slum",
    location: "Chennai, India",
    camera: "Nikon D90",
    orientation: "horizontal",
  },
  {
    type: "photo",
    id: "travel/3299396187_97ccd37f7b_b.jpg",
    category: "travel",
    title: "Stupa",
    location: "Mae Hong Son, Thailand",
    camera: "Diana Camera",
  },
  {
    type: "photo",
    id: "travel/3328489362_3d5ae9bfcb_b.jpg",
    category: "travel",
    title: "Novice",
    location: "Burma",
    camera: "Kiev 60 TTL",
  },
  {
    type: "photo",
    id: "travel/190747690_73868f6030_o.jpg",
    category: "travel",
    title: "untitled",
    location: "La Vega, Dominican Republic",
    camera: "Holga",
  },
  {
    type: "photo",
    id: "travel/3328487560_0e6a9d531b_b.jpg",
    category: "travel",
    title: "school kids",
    location: "Burma",
    camera: "Kiev 60 TTL",
  },
  {
    type: "photo",
    id: "travel/23850487005_2f01363c08_b.jpg",
    category: "travel",
    title: "Untitled",
    camera: "Nikon D90",
    orientation: "vertical",
  },
  {
    type: "photo",
    id: "travel/4126993858_c1373fd1d3_b.jpg",
    category: "travel",
    title: "orphans",
    location: "Pamuru, India",
    camera: "Nikon D90",
    orientation: "horizontal",
  },
  {
    type: "photo",
    id: "travel/2419658284_e6be1581cd.jpg",
    category: "travel",
    title: "untitled",
    location: "Hawaii",
    camera: "Kiev 60 TTL",
  },
  {
    type: "photo",
    id: "travel/4426186198_e77b78c700_o.jpg",
    category: "travel",
    title: "Karala backwaters",
    location: "Karala, India",
    camera: "Diana Camera",
  },
  {
    type: "photo",
    id: "travel/425235929_45bb321eb5_b.jpg",
    category: "travel",
    title: "Pai bus",
    location: "Pai, Thailand",
    camera: "Nikon D70",
    orientation: "horizontal",
  },
  {
    type: "photo",
    id: "travel/423216025_33d8943efe_o.jpg",
    category: "travel",
    title: "bamboo",
    location: "Pai, Thailand",
    camera: "Holga",
  },
  {
    type: "photo",
    id: "life/23677757865_4cf39c45a4_b.jpg",
    category: "travel",
    title: "Untitled",
    camera: "Nikon D90",
    orientation: "horizontal",
  },
  {
    type: "photo",
    id: "life/7730432316_f728bbff58_b.jpg",
    category: "life",
    title: "Sue",
    location: "Redondo Beach, CA",
    camera: "Nikon D90",
    orientation: "vertical",
  },
  {
    type: "photo",
    id: "life/66647806_d42b761c02_o.jpg",
    category: "life",
    title: "untitled",
    camera: "fujica",
    orientation: "vertical",
  },
  {
    type: "photo",
    id: "life/3613778427_38b14696eb_b.jpg",
    category: "life",
    title: "untitled",
    location: "Bethel, VT",
    camera: "Kiev 60 TTL",
  },
  {
    type: "photo",
    id: "life/7737315806_a19e7af564_b.jpg",
    category: "life",
    title: "Sue",
    location: "Redondo Beach, CA",
    camera: "Nikon D90",
    orientation: "vertical",
  },
  {
    type: "photo",
    id: "life/182444495_f8da423932_b.jpg",
    category: "life",
    title: "Nedia",
    camera: "Yashica Electro",
    orientation: "vertical",
  },
  {
    type: "photo",
    id: "life/2546430828_a764bee6be_o.jpg",
    category: "life",
    title: "Alex Toth",
    location: "Burlington, VT",
    camera: "Kiev 60 TTL",
  },
  {
    type: "photo",
    id: "bands/21601462960_81675438f1_h.jpg",
    category: "bands",
    title: "The Pham Entertainment Artists",
    location: "Los Angeles, CA",
    camera: "Nikon D90",
    orientation: "vertical",
  },
  {
    type: "photo",
    id: "bands/2546592236_144d013dc2_o.jpg",
    category: "bands",
    title: "Rubblebucket",
    camera: "kiev 60 ttl",
  },
  {
    type: "photo",
    id: "bands/3449012140_ebfbc1a8dc_b.jpg",
    category: "bands",
    title: "Myra Flynn",
    camera: "kiev 60 ttl",
  },
  {
    type: "photo",
    id: "bands/4109568218_010e24e2e5_o.jpg",
    category: "bands",
    title: "Hunter and Fereale",
    camera: "Holga",
  },
  {
    type: "photo",
    id: "bands/3544245534_5169922df9_b.jpg",
    category: "bands",
    title: "Rubblebucket",
    camera: "Kiev 60 TTL",
  },
  {
    type: "video",
    title: "Kiefer Why not? Bass Cover",
    id: "2u8cAGSMFjE",
    orientation: "horizontal",
  },
  {
    type: "video",
    title: "If These Walls Could Talk",
    id: "X5thM_ze_a4",
    orientation: "horizontal",
  },
  {
    type: "video",
    title: "Slum Village - 2U4U",
    id: "mpcZOL9FwlA",
    orientation: "horizontal",
  },
  {
    type: "video",
    title: "Jorja Smith Bass Cover",
    id: "hXEyn5RnhUk",
    orientation: "horizontal",
  },
  {
    type: "video",
    title: "Autumn Leaves",
    id: "tx8BlCl24d4",
    orientation: "horizontal",
  },
  {
    type: "video",
    title: "Slumn Village - Tell Me",
    id: "xjaP1YyP3nU",
    orientation: "horizontal",
  },
  {
    type: "video",
    title: "Slum Village - Get Dis Money",
    id: "HvR63gjhI1c",
    orientation: "horizontal",
  },
  {
    type: "video",
    title: "Voodoo Man",
    id: "NbxYr3_i1SU",
    orientation: "horizontal",
  },
];

// soundcloud.com/108villains/pepto?in=108villains/sets/for-ariana/s-Ahh29uxpf6c&si=13de373264c04281bfc3202fc7e16bff&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing
// soundcloud.com/108villains/take-your-time-ariana-blanco?si=4de322cd668b4d12893735eaf512073d&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing
//soundcloud.com/108villains/princess?si=0f61dfd338c34b9e96d4cbb51c2cc64a&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing
//soundcloud.com/108villains/stbb30-knockout-ned?si=1e99758281974675837bc02f7ea57c93&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing
//soundcloud.com/108villains/stbb-627-chicken-and-waffles?si=f01d03a02a2147e0ac102f1fb2971a8a&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing
export default photos;
