import { Photo } from "@/types";

const photos: Photo[] = [
  {
    type: "image",
    id: "travel/6300318366_0ef0aa65de_b.jpg",
    category: "travel",
    title: "Hermosa Beach",
    location: "Hermosa Beach, CA",
    camera: "Diana Camera",
  },
  {
    type: "image",
    id: "travel/3257423319_7b723c6320_b.jpg",
    category: "travel",
    title: "White temple",
    location: "Chiang Rai, Thailand",
    camera: "Diana Camera",
  },
  {
    type: "image",
    id: "travel/422072087_22ea7f952a_b.jpg",
    category: "travel",
    title: "blind musician",
    location: "Bangkok, Thailand",
    camera: "Nikon D70",
    orientation: "vertical",
  },
  {
    type: "image",
    id: "travel/4571721717_bb4f9da01a_b.jpg",
    category: "travel",
    title: "Astronomy park",
    location: "Jaipur, India",
    camera: "Olympus XA",
    orientation: "horizontal",
  },
  {
    type: "image",
    id: "life/23446229681_fcfcb9d7d3_b.jpg",
    category: "life",
    title: "Untitled",
    camera: "Nikon D90",
    orientation: "vertical",
  },
  {
    type: "image",
    id: "travel/3272890577_a2d4fb7fef_b.jpg",
    category: "travel",
    title: "Doi Suthep",
    location: "Chiang Mai, Thailand",
    camera: "Diana Camera",
  },
  {
    type: "image",
    id: "travel/3269066068_0d308a7f1a_b.jpg",
    category: "travel",
    title: "Untitled",
    location: "Chiang Mai, Thailand",
    camera: "Diana Camera",
  },
  {
    type: "image",
    id: "travel/4619264427_62b8a23c57_b.jpg",
    category: "travel",
    title: "untitled",
    location: "India",
    camera: "Olympus XA",
    orientation: "horizontal",
  },
  {
    type: "image",
    id: "travel/4405365546_e1002b5010_b.jpg",
    category: "travel",
    title: "Pallam Slum",
    location: "Chennai, India",
    camera: "Nikon D90",
    orientation: "horizontal",
  },
  {
    type: "image",
    id: "travel/3299396187_97ccd37f7b_b.jpg",
    category: "travel",
    title: "Stupa",
    location: "Mae Hong Son, Thailand",
    camera: "Diana Camera",
  },
  {
    type: "image",
    id: "travel/3328489362_3d5ae9bfcb_b.jpg",
    category: "travel",
    title: "Novice",
    location: "Burma",
    camera: "Kiev 60 TTL",
  },
  {
    type: "image",
    id: "travel/190747690_73868f6030_o.jpg",
    category: "travel",
    title: "untitled",
    location: "La Vega, Dominican Republic",
    camera: "Holga",
  },
  {
    type: "image",
    id: "travel/3328487560_0e6a9d531b_b.jpg",
    category: "travel",
    title: "school kids",
    location: "Burma",
    camera: "Kiev 60 TTL",
  },
  {
    type: "image",
    id: "travel/23850487005_2f01363c08_b.jpg",
    category: "travel",
    title: "Untitled",
    camera: "Nikon D90",
    orientation: "vertical",
  },
  {
    type: "image",
    id: "travel/4126993858_c1373fd1d3_b.jpg",
    category: "travel",
    title: "orphans",
    location: "Pamuru, India",
    camera: "Nikon D90",
    orientation: "horizontal",
  },
  {
    type: "image",
    id: "travel/2419658284_e6be1581cd.jpg",
    category: "travel",
    title: "untitled",
    location: "Hawaii",
    camera: "Kiev 60 TTL",
  },
  {
    type: "image",
    id: "travel/4426186198_e77b78c700_o.jpg",
    category: "travel",
    title: "backwaters",
    location: "Karala, India",
    camera: "Diana Camera",
  },
  {
    type: "image",
    id: "travel/425235929_45bb321eb5_b.jpg",
    category: "travel",
    title: "Pai bus",
    location: "Pai, Thailand",
    camera: "Nikon D70",
    orientation: "horizontal",
  },
  {
    type: "image",
    id: "travel/423216025_33d8943efe_o.jpg",
    category: "travel",
    title: "bamboo",
    location: "Pai, Thailand",
    camera: "Holga",
  },
  {
    type: "image",
    id: "travel/23229339384_b184c5b0d0_b.jpg",
    category: "travel",
    title: "Untitled",
    camera: "Nikon D90",
    orientation: "horizontal",
  },
  {
    type: "image",
    id: "life/7730432316_f728bbff58_b.jpg",
    category: "life",
    title: "Sue",
    location: "Redondo Beach, CA",
    camera: "Nikon D90",
    orientation: "vertical",
  },
  {
    type: "image",
    id: "life/66647806_d42b761c02_o.jpg",
    category: "life",
    title: "untitled",
    camera: "fujica",
    orientation: "vertical",
  },
  {
    type: "image",
    id: "life/3613778427_38b14696eb_b.jpg",
    category: "life",
    title: "untitled",
    location: "Bethel, VT",
    camera: "Kiev 60 TTL",
  },
  {
    type: "image",
    id: "life/7737315806_a19e7af564_b.jpg",
    category: "life",
    title: "Sue",
    location: "Redondo Beach, CA",
    camera: "Nikon D90",
    orientation: "vertical",
  },
  {
    type: "image",
    id: "life/182444495_f8da423932_b.jpg",
    category: "life",
    title: "Nedia",
    camera: "Yashica Electro",
    orientation: "vertical",
  },
  {
    type: "image",
    id: "life/2546430828_a764bee6be_o.jpg",
    category: "life",
    title: "Alex Toth",
    location: "Burlington, VT",
    camera: "Kiev 60 TTL",
  },
  {
    type: "image",
    id: "bands/21601462960_81675438f1_h.jpg",
    category: "bands",
    title: "The Pham Entertainment Artists",
    location: "Los Angeles, CA",
    camera: "Nikon D90",
    orientation: "vertical",
  },
  {
    type: "image",
    id: "bands/2546592236_144d013dc2_o.jpg",
    category: "bands",
    title: "Rubblebucket",
    camera: "kiev 60 ttl",
  },
  {
    type: "image",
    id: "bands/3449012140_ebfbc1a8dc_b.jpg",
    category: "bands",
    title: "Myra Flynn",
    camera: "kiev 60 ttl",
  },
  {
    type: "image",
    id: "bands/4109568218_010e24e2e5_o.jpg",
    category: "bands",
    title: "Hunter and Fereale",
    camera: "Holga",
  },
  {
    type: "image",
    id: "bands/3544245534_5169922df9_b.jpg",
    category: "bands",
    title: "Rubblebucket",
    camera: "Kiev 60 TTL",
  },
  // {
  //   type: "image",
  //   id: "bands/24850613076_f51a6f30a1_b.jpg",
  //   category: "bands",
  //   title: "Justin Levinson",
  //   location: "Los Angeles, CA",
  //   camera: "Nikon D90",
  //   orientation: "horizontal",
  // },
  // {
  //   type: "image",
  //   id: "travel/4364031123_ba885c6583_b.jpg",
  //   category: "travel",
  //   title: "Pallam Slum",
  //   location: "Chennai, India",
  //   camera: "Nikon D90",
  //   orientation: "horizontal",
  // },
  // {
  //   type: "image",
  //   id: "travel/440709028_3f7682b065_b.jpg",
  //   category: "travel",
  //   title: "Wat Umong",
  //   location: "Chiang Mai, Thailand",
  //   camera: "Nikon D70",
  //   orientation: "horizontal",
  // },
];

export default photos;
